version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: ./install_requirements
      runas: root
  ApplicationStart:
    - location: ./start_server.sh
      runas: root
